const data = [
  {
    name: "D.Va",
    icon: "icons/tank/D.Va.webp",
    role: "tank",
    counterpicks: [
      "Zarya",
      "Sigma",
      "Roadhog",
      "Sombra",
      "Symmetra",
      "Tracer",
      "Baptiste",
      "Zenyatta",
      "Brigitte",
    ],
  },
  {
    name: "Doomfist",
    icon: "icons/tank/Doomfist.webp",
    role: "tank",
    counterpicks: [
      "Roadhog",
      "Orisa",
      "Reinhardt",
      "Sombra",
      "Pharah",
      "Reaper",
      "Ana",
      "Brigitte",
      "Mercy",
    ],
  },
  {
    name: "Junker Queen",
    icon: "icons/tank/Junker_Queen.webp",
    role: "tank",
    counterpicks: [
      "Reinhardt",
      "Zarya",
      "Sigma",
      "Ashe",
      "Sojourn",
      "Widowmaker",
      "Lucio",
      "Kiriko",
      "Ana",
    ],
  },
  {
    name: "Orisa",
    icon: "icons/tank/Orisa.webp",
    role: "tank",
    counterpicks: [
      "Zarya",
      "Sigma",
      "Junker Queen",
      "Pharah",
      "Ashe",
      "Widowmaker",
      "Baptiste",
      "Lucio",
      "Zenyatta",
    ],
  },
  {
    name: "Reinhardt",
    icon: "icons/tank/Reinhardt.webp",
    role: "tank",
    counterpicks: [
      "Orisa",
      "Wrecking Ball",
      "Winston",
      "Sojourn",
      "Sombra",
      "Symmetra",
      "Kiriko",
      "Lucio",
      "Ana",
    ],
  },
  {
    name: "Roadhog",
    icon: "icons/tank/Roadhog.webp",
    role: "tank",
    counterpicks: [
      "Zarya",
      "Sigma",
      "Orisa",
      "Reaper",
      "Hanzo",
      "Pharah",
      "Ana",
      "Zenyatta",
      "Kiriko",
    ],
  },
  {
    name: "Sigma",
    icon: "icons/tank/Sigma.webp",
    role: "tank",
    counterpicks: [
      "Zarya",
      "Winston",
      "Junker Queen",
      "Sombra",
      "Pharah",
      "Echo",
      "Lucio",
      "Zenyatta",
      "Brigitte",
    ],
  },
  {
    name: "Winston",
    icon: "icons/tank/Winston.webp",
    role: "tank",
    counterpicks: [
      "Roadhog",
      "D.Va",
      "Junker Queen",
      "Reaper",
      "Sojourn",
      "Echo",
      "Ana",
      "Zenyatta",
      "Mercy",
    ],
  },
  {
    name: "Wrecking Ball",
    icon: "icons/tank/Wrecking_Ball.webp",
    role: "tank",
    counterpicks: [
      "Roadhog",
      "D.Va",
      "Doomfist",
      "Sombra",
      "Reaper",
      "Mei",
      "Ana",
      "Lucio",
      "Brigitte",
    ],
  },
  {
    name: "Zarya",
    icon: "icons/tank/Zarya.webp",
    role: "tank",
    counterpicks: [
      "Winston",
      "Wrecking Ball",
      "Reinhardt",
      "Widowmaker",
      "Tracer",
      "Pharah",
      "Lucio",
      "Zenyatta",
      "Brigitte",
    ],
  },
  {
    name: "Ashe",
    icon: "icons/damage/Ashe.webp",
    role: "damage",
    counterpicks: [
      "Sigma",
      "Winston",
      "Doomfist",
      "Widowmaker",
      "Hanzo",
      "Sojourn",
      "Ana",
      "Mercy",
      "Zenyatta",
    ],
  },
  {
    name: "Bastion",
    icon: "icons/damage/Bastion.webp",
    role: "damage",
    counterpicks: [
      "D.Va",
      "Sigma",
      "Orisa",
      "Sojourn",
      "Hanzo",
      "Tracer",
      "Zenyatta",
      "Lucio",
      "Kiriko",
    ],
  },
  {
    name: "Cassidy",
    icon: "icons/damage/Cassidy.webp",
    role: "damage",
    counterpicks: [
      "Sigma",
      "Roadhog",
      "Orisa",
      "Widowmaker",
      "Hanzo",
      "Sojourn",
      "Zenyatta",
      "Baptiste",
      "Kiriko",
    ],
  },
  {
    name: "Echo",
    icon: "icons/damage/Echo.webp",
    role: "damage",
    counterpicks: [
      "D.Va",
      "Roadhog",
      "Ramattra",
      "Ashe",
      "Soldier: 76",
      "Widowmaker",
      "Mercy",
      "Ana",
      "Baptiste",
    ],
  },
  {
    name: "Genji",
    icon: "icons/damage/Genji.webp",
    role: "damage",
    counterpicks: [
      "Winston",
      "Zarya",
      "Roadhog",
      "Pharah",
      "Torbjorn",
      "Cassidy",
      "Lucio",
      "Moira",
      "Kiriko",
    ],
  },
  {
    name: "Hanzo",
    icon: "icons/damage/Hanzo.webp",
    role: "damage",
    counterpicks: [
      "Sigma",
      "D.Va",
      "Doomfist",
      "Pharah",
      "Echo",
      "Tracer",
      "Mercy",
      "Zenyatta",
      "Lucio",
    ],
  },
  {
    name: "Junkrat",
    icon: "icons/damage/Junkrat.webp",
    role: "damage",
    counterpicks: [
      "D.Va",
      "Zarya",
      "Orisa",
      "Pharah",
      "Echo",
      "Widowmaker",
      "Baptiste",
      "Kiriko",
      "Ana",
    ],
  },
  {
    name: "Mei",
    icon: "icons/damage/Mei.webp",
    role: "damage",
    counterpicks: [
      "Doomfist",
      "Winston",
      "Orisa",
      "Pharah",
      "Hanzo",
      "Widowmaker",
      "Baptiste",
      "Kiriko",
      "Zenyatta",
    ],
  },
  {
    name: "Pharah",
    icon: "icons/damage/Pharah.webp",
    role: "damage",
    counterpicks: [
      "D.Va",
      "Wrecking Ball",
      "Ramattra",
      "Echo",
      "Widowmaker",
      "Soldier: 76",
      "Mercy",
      "Baptiste",
      "Ana",
    ],
  },
  {
    name: "Reaper",
    icon: "icons/damage/Reaper.webp",
    role: "damage",
    counterpicks: [
      "Zarya",
      "Orisa",
      "Reinhardt",
      "Pharah",
      "Echo",
      "Ashe",
      "Lucio",
      "Ana",
      "Brigitte",
    ],
  },
  {
    name: "Sojourn",
    icon: "icons/damage/Sojourn.webp",
    role: "damage",
    counterpicks: [
      "D.Va",
      "Doomfist",
      "Orisa",
      "Widowmaker",
      "Hanzo",
      "Genji",
      "Mercy",
      "Lucio",
      "Baptiste",
    ],
  },
  {
    name: "Soldier: 76",
    icon: "icons/damage/Soldier_76.webp",
    role: "damage",
    counterpicks: [
      "Doomfist",
      "Winston",
      "D.Va",
      "Widowmaker",
      "Hanzo",
      "Ashe",
      "Zenyatta",
      "Ana",
      "Lucio",
    ],
  },
  {
    name: "Sombra",
    icon: "icons/damage/Sombra.webp",
    role: "damage",
    counterpicks: [
      "Zarya",
      "Winston",
      "Junker Queen",
      "Hanzo",
      "Sojourn",
      "Torbjorn",
      "Ana",
      "Kiriko",
      "Brigitte",
    ],
  },
  {
    name: "Symmetra",
    icon: "icons/damage/Symmetra.webp",
    role: "damage",
    counterpicks: [
      "Roadhog",
      "Zarya",
      "Orisa",
      "Sombra",
      "Pharah",
      "Echo",
      "Lucio",
      "Mercy",
      "Moira",
    ],
  },
  {
    name: "Torbjorn",
    icon: "icons/damage/Torbjorn.webp",
    role: "damage",
    counterpicks: [
      "Orisa",
      "Sigma",
      "Roadhog",
      "Hanzo",
      "Soldier: 76",
      "Pharah",
      "Lucio",
      "Zenyatta",
      "Kiriko",
    ],
  },
  {
    name: "Tracer",
    icon: "icons/damage/Tracer.webp",
    role: "damage",
    counterpicks: [
      "Roadhog",
      "Orisa",
      "Doomfist",
      "Torbjorn",
      "Soldier: 76",
      "Ashe",
      "Kiriko",
      "Baptiste",
      "Moira",
    ],
  },
  {
    name: "Widowmaker",
    icon: "icons/damage/Widowmaker.webp",
    role: "damage",
    counterpicks: [
      "Wrecking Ball",
      "Winston",
      "Sigma",
      "Genji",
      "Tracer",
      "Sombra",
      "Lucio",
      "Mercy",
      "Kiriko",
    ],
  },
  {
    name: "Ana",
    icon: "icons/support/Ana.webp",
    role: "support",
    counterpicks: [
      "D.Va",
      "Zarya",
      "Sigma",
      "Widowmaker",
      "Hanzo",
      "Sojourn",
      "Kiriko",
      "Lucio",
      "Baptiste",
    ],
  },
  {
    name: "Baptiste",
    icon: "icons/support/Baptiste.webp",
    role: "support",
    counterpicks: [
      "Wrecking Ball",
      "Doomfist",
      "Winston",
      "Hanzo",
      "Ashe",
      "Widowmaker",
      "Zenyatta",
      "Lucio",
      "Kiriko",
    ],
  },
  {
    name: "Brigitte",
    icon: "icons/support/Brigitte.webp",
    role: "support",
    counterpicks: [
      "Reinhardt",
      "Zarya",
      "Sigma",
      "Pharah",
      "Soldier: 76",
      "Sojourn",
      "Lucio",
      "Moira",
      "Zenyatta",
    ],
  },
  {
    name: "Kiriko",
    icon: "icons/support/Kiriko.webp",
    role: "support",
    counterpicks: [
      "Sigma",
      "Wrecking Ball",
      "Winston",
      "Hanzo",
      "Sojourn",
      "Echo",
      "Moira",
      "Brigitte",
      "Zenyatta",
    ],
  },
  {
    name: "Lucio",
    icon: "icons/support/Lucio.webp",
    role: "support",
    counterpicks: [
      "Roadhog",
      "Winston",
      "Doomfist",
      "Sombra",
      "Pharah",
      "Cassidy",
      "Moira",
      "Kiriko",
      "Mercy",
    ],
  },
  {
    name: "Mercy",
    icon: "icons/support/Mercy.webp",
    role: "support",
    counterpicks: [
      "D.Va",
      "Roadhog",
      "Wrecking Ball",
      "Soldier: 76",
      "Cassidy",
      "Tracer",
      "Ana",
      "Baptiste",
      "Moira",
    ],
  },
  {
    name: "Moira",
    icon: "icons/support/Moira.webp",
    role: "support",
    counterpicks: [
      "Roadhog",
      "Reinhardt",
      "Zarya",
      "Sombra",
      "Pharah",
      "Widowmaker",
      "Ana",
      "Baptiste",
      "Zenyatta",
    ],
  },
  {
    name: "Zenyatta",
    icon: "icons/support/Zenyatta.webp",
    role: "support",
    counterpicks: [
      "Junker Queen",
      "Reinhardt",
      "Doomfist",
      "Sombra",
      "Tracer",
      "Widowmaker",
      "Ana",
      "Lucio",
      "Mercy",
    ],
  },
];

export default data;
